# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # Runs a single command using the runners shell
    - name: setup git config
      run: |
        git config user.name "Sadanand Pai"
        git config user.email "sadypai@gmail.com"
        
    # Runs a set of commands using the runners shell
    - name: setup deployment
      run: |
        npm ci
        rm -rf dist
        npm run build
        git add dist -f
        git commit -m "build files from github action"
        git push
  
